name: Build and Push a Docker Image

on:
  push:
    branches: [ main ]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cloudchipr/cli:$GITHUB_SHA --tag cloudchipr/cli:latest
        docker push -a cloudchipr/cli
